#!/bin/bash

set -euo pipefail

repo_dir=$(git rev-parse --show-toplevel)
name=$(basename "$repo_dir")-test

docker build -t "$name" "$repo_dir/test"
docker run --rm -v "$repo_dir":/work -w /work "$name" pytest -v test/
