---
name: Test
on:
  workflow_dispatch:
  push:
    branches-ignore:
      - 'dependabot/**'

jobs:
  publish:
    name: Test
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/master' }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
      - uses: BSFishy/pip-action@v1
        with:
          packages: |
            docker
      - run: ./test/run
